version: "2.2"
services:
  cherrywatch:
    container_name: cherrywatch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    environment:
      - ACCOUNT_SID=${ACCOUNT_SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - RECIPIENTS=${RECIPIENTS}
      - LOG_LEVEL=debug
