name: Notifies users of changes to the cherry blossom map
on:
  schedule:
    - cron: '0 8,12,16,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID}}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Generate snapshot
      run: yarn test

    - name: Update image snapshots on failure
      if: failure()
      run: yarn test -u

    - name: Commit new files
      if: always()
      run: |
          git config --global user.name 'Jennifer Kaplan'
          git config --global user.email 'jennyckaplan@users.noreply.github.com'
          git add .
          git commit -am "updated images" --allow-empty
          git push --force origin main

    - name: Notify users of updates to map
      if: failure()
      uses: ./docker
