name: Gets most up to date Cherry Blossom map
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Generate snapshot
      run: yarn test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Upload artifacts
        path: __image_snapshots__/__diff_output__
