name: Gets most up to date Cherry Blossom map
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Generate snapshot
      run: yarn test
    - name: Commit new files
      if: failure()
      run: |
          git config --global user.name 'Jennifer Kaplan'
          git config --global user.email 'jennyckaplan@users.noreply.github.com'
          git checkout -b jck/testing
          git commit -am "updated images"
          git push origin jck/testing
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Upload artifacts
        path: __image_snapshots__/__diff_output__
