name: Notifies users of changes to the cherry blossom map
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID}}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Generate snapshot
      run: yarn test

    - name: Update image snapshots on failure
      if: failure()
      run: yarn test -u

    - name: Commit new files
      if: failure()
      run: |
          git config --global user.name 'Jennifer Kaplan'
          git config --global user.email 'jennyckaplan@users.noreply.github.com'
          git commit -am "updated images"
          git push --force origin main

    - name: Notify users of updates to map
      if: failure()
      uses: ./docker
