name: Gets most up to date Cherry Blossom map
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Generate snapshot
      run: yarn test
    - name: Update image snapshots on failure
      if: failure()
      run: yarn test -u
    - name: Commit new files
      if: failure()
      run: |
          git config --global user.name 'Jennifer Kaplan'
          git config --global user.email 'jennyckaplan@users.noreply.github.com'
          git commit -am "updated images"
          git push --force origin main
